<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<c:set var="pageTitle" value="Management Reports" scope="request"/>
<jsp:include page="/WEB-INF/views/includes/header.jsp"/>

<section class="page-heading no-print"><div><span class="eyebrow">Decision support</span><h1>Management reports</h1><p>Analyse appointments, patients, treatments, dentist workload and clinic revenue.</p></div><button class="button button-secondary" type="button" data-print>Print report</button></section>

<section class="panel no-print"><form class="report-filter" method="get" action="${pageContext.request.contextPath}/reports"><div class="field"><label for="from">From date</label><input id="from" name="from" type="date" value="${fromDate}" required></div><div class="field"><label for="to">To date</label><input id="to" name="to" type="date" value="${toDate}" required></div><button class="button button-primary" type="submit">Generate report</button></form></section>
<c:if test="${not empty error}"><div class="alert alert-error"><c:out value="${error}"/></div></c:if>

<c:if test="${not empty report}">
<section class="report-document">
    <header class="report-print-header"><div class="brand"><span class="brand-mark">SD</span><span><strong>Sunrise Dental Clinic</strong><small>Management Performance Report</small></span></div><div><strong><c:out value="${report.fromDate()}"/> to <c:out value="${report.toDate()}"/></strong><small>Generated by <c:out value="${currentUser.fullName()}"/></small></div></header>

    <section class="metric-grid">
        <article class="metric-card"><span>Total appointments</span><strong><c:out value="${report.totalAppointments()}"/></strong><small><c:out value="${report.completedAppointments()}"/> completed</small></article>
        <article class="metric-card"><span>New patients</span><strong><c:out value="${report.newPatients()}"/></strong><small>Registered in selected period</small></article>
        <article class="metric-card"><span>Revenue received</span><strong>LKR <c:out value="${report.receivedAmount()}"/></strong><small>Invoiced: LKR <c:out value="${report.invoicedAmount()}"/></small></article>
        <article class="metric-card"><span>Outstanding</span><strong>LKR <c:out value="${report.outstandingAmount()}"/></strong><small>Unpaid invoice balance</small></article>
    </section>

    <section class="panel report-status"><div class="panel-header"><div><span class="eyebrow">Appointment outcomes</span><h2>Status distribution</h2></div></div><div class="status-summary"><div><span>Scheduled</span><strong><c:out value="${report.scheduledAppointments()}"/></strong></div><div><span>Completed</span><strong><c:out value="${report.completedAppointments()}"/></strong></div><div><span>Cancelled</span><strong><c:out value="${report.cancelledAppointments()}"/></strong></div><div><span>No-show</span><strong><c:out value="${report.noShowAppointments()}"/></strong></div></div></section>

    <section class="content-grid">
        <article class="panel"><div class="panel-header"><div><span class="eyebrow">Clinical demand</span><h2>Treatment activity</h2></div></div><c:choose><c:when test="${empty report.treatmentActivity()}"><div class="empty-state">No treatment activity in this period.</div></c:when><c:otherwise><div class="table-wrap"><table><thead><tr><th>Treatment</th><th>Quantity</th><th class="align-right">Booked value</th></tr></thead><tbody><c:forEach var="row" items="${report.treatmentActivity()}"><tr><td><c:out value="${row.label()}"/></td><td><c:out value="${row.activityCount()}"/></td><td class="align-right">LKR <c:out value="${row.amount()}"/></td></tr></c:forEach></tbody></table></div></c:otherwise></c:choose></article>
        <article class="panel"><div class="panel-header"><div><span class="eyebrow">Workload</span><h2>Dentist performance</h2></div></div><div class="table-wrap"><table><thead><tr><th>Dentist</th><th>Appointments</th><th class="align-right">Invoiced</th></tr></thead><tbody><c:forEach var="row" items="${report.dentistActivity()}"><tr><td><c:out value="${row.label()}"/></td><td><c:out value="${row.activityCount()}"/></td><td class="align-right">LKR <c:out value="${row.amount()}"/></td></tr></c:forEach></tbody></table></div></article>
    </section>

    <section class="panel"><div class="panel-header"><div><span class="eyebrow">Cash flow</span><h2>Daily payments</h2></div></div><c:choose><c:when test="${empty report.dailyRevenue()}"><div class="empty-state">No payments were recorded in this period.</div></c:when><c:otherwise><div class="revenue-bars"><c:forEach var="day" items="${report.dailyRevenue()}"><div class="revenue-row"><span><c:out value="${day.dateDisplay()}"/></span><div><i></i></div><strong>LKR <c:out value="${day.amount()}"/></strong></div></c:forEach></div></c:otherwise></c:choose></section>
</section>
</c:if>

<jsp:include page="/WEB-INF/views/includes/footer.jsp"/>
