<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<c:set var="pageTitle" value="Treatments" scope="request"/>
<jsp:include page="/WEB-INF/views/includes/header.jsp"/>

<section class="page-heading"><div><span class="eyebrow">Clinical catalogue</span><h1>Treatment management</h1><p>Maintain the services and standard fees used for appointments and invoices.</p></div></section>
<c:if test="${not empty success}"><div class="alert alert-success"><c:out value="${success}"/></div></c:if>
<c:if test="${not empty error}"><div class="alert alert-error"><c:out value="${error}"/></div></c:if>

<section class="panel form-panel"><div class="panel-header"><div><span class="eyebrow">Catalogue</span><h2>Add treatment</h2></div></div><form class="form-grid" method="post" action="${pageContext.request.contextPath}/treatments"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="save"><div class="field"><label for="treatmentCode">Code <span>*</span></label><input id="treatmentCode" name="treatmentCode" maxlength="20" placeholder="TRT-007" required></div><div class="field"><label for="treatmentName">Treatment name <span>*</span></label><input id="treatmentName" name="treatmentName" maxlength="100" required></div><div class="field"><label for="standardFee">Standard fee (LKR) <span>*</span></label><input id="standardFee" name="standardFee" type="number" min="0" step="0.01" required></div><div class="field"><label for="description">Description</label><input id="description" name="description" maxlength="255"></div><div class="form-actions field-span-2"><button class="button button-primary" type="submit">Add treatment</button></div></form></section>

<section class="panel"><div class="panel-header"><div><span class="eyebrow">Current services</span><h2>Treatment catalogue</h2></div><span class="record-count"><c:out value="${fn:length(treatments)}"/> treatments</span></div><div class="table-wrap"><table><thead><tr><th>Code</th><th>Treatment details</th><th>Standard fee</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<c:forEach var="treatment" items="${treatments}"><tr><td><strong><c:out value="${treatment.treatmentCode()}"/></strong></td><td><strong><c:out value="${treatment.treatmentName()}"/></strong><small class="table-subtext"><c:out value="${treatment.description()}"/></small></td><td>LKR <c:out value="${treatment.standardFee()}"/></td><td><span class="status ${treatment.active() ? 'status-active' : 'status-cancelled'}">${treatment.active() ? 'ACTIVE' : 'INACTIVE'}</span></td><td><div class="table-actions"><form method="post" action="${pageContext.request.contextPath}/treatments"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="toggle"><input type="hidden" name="treatmentId" value="${treatment.treatmentId()}"><input type="hidden" name="active" value="${!treatment.active()}"><button class="button button-small button-secondary" type="submit">${treatment.active() ? 'Deactivate' : 'Activate'}</button></form></div></td></tr></c:forEach>
</tbody></table></div><p class="form-note">Changing a standard fee does not alter charges already saved against earlier appointments.</p></section>

<section class="panel"><div class="panel-header"><div><span class="eyebrow">Maintenance</span><h2>Edit existing treatment</h2></div></div><div class="edit-card-list"><c:forEach var="treatment" items="${treatments}"><details class="edit-card"><summary><strong><c:out value="${treatment.treatmentCode()} | ${treatment.treatmentName()}"/></strong><span>LKR <c:out value="${treatment.standardFee()}"/></span></summary><form class="form-grid" method="post" action="${pageContext.request.contextPath}/treatments"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="save"><input type="hidden" name="treatmentId" value="${treatment.treatmentId()}"><div class="field"><label>Code</label><input name="treatmentCode" maxlength="20" value="${fn:escapeXml(treatment.treatmentCode())}" required></div><div class="field"><label>Name</label><input name="treatmentName" maxlength="100" value="${fn:escapeXml(treatment.treatmentName())}" required></div><div class="field"><label>Standard fee</label><input name="standardFee" type="number" min="0" step="0.01" value="${treatment.standardFee()}" required></div><div class="field"><label>Description</label><input name="description" maxlength="255" value="${fn:escapeXml(treatment.description())}"></div><div class="form-actions field-span-2"><button class="button button-primary" type="submit">Save treatment changes</button></div></form></details></c:forEach></div></section>
<jsp:include page="/WEB-INF/views/includes/footer.jsp"/>
