package com.sunrisedental.model;

public enum Permission {
    VIEW_DASHBOARD,
    VIEW_PATIENTS,
    MANAGE_PATIENTS,
    VIEW_APPOINTMENTS,
    MANAGE_APPOINTMENTS,
    UPDATE_APPOINTMENT_STATUS,
    VIEW_BILLING,
    MANAGE_BILLING,
    MANAGE_TREATMENTS,
    MANAGE_STAFF,
    VIEW_REPORTS,
    VIEW_NOTIFICATIONS,
    VIEW_HELP
}
